# Generated by Django 4.1 on 2022-08-18 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Not read'), (1, 'Read'), (2, 'Applied'), (3, 'Denied'), (4, 'Archived')], default=0)),
                ('grade', models.IntegerField(default=None, null=True)),
                ('speciality', models.CharField(max_length=255)),
                ('salary', models.IntegerField(default=None, null=True)),
                ('education', models.CharField(max_length=255)),
                ('experience', models.CharField(max_length=255)),
                ('portfolio', models.CharField(default=None, max_length=1000, null=True)),
                ('title', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
